<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'jsontopgnparser' => '/JsonToPgnParser.php',
                'chess_json' => '/CHESS_JSON.php',
                'board0x88config' => '/Board0x88Config.php',
                'dgtgameparser' => '/DGTGameParser.php',
                'fenparser0x88' => '/FenParser0x88.php',
                'gameparser' => '/GameParser.php',
                'movebuilder' => '/MoveBuilder.php',
                'moveparser' => '/MoveParser.php',
                'parsertest' => '/test/ParserTest.php',
                'pgngameparser' => '/PgnGameParser.php',
                'pgnparser' => '/PgnParser.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd